# ========================================
# === BLOC DE CONFIGURATION COMMUNE AIRFLOW
# ========================================
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.3.2}
  build: ./airflow  # Permet l’extension via Dockerfile personnalisé si besoin
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-run-postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-run-postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://airflow-run-redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/mlflow:/opt/airflow/mlflow
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    airflow-run-redis:
      condition: service_healthy
    airflow-run-postgres:
      condition: service_healthy

# ========================================
# === SERVICES DE BASE DE DONNÉES
# ========================================
services:
  airflow-run-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    env_file:
      - .env
    volumes:
      - ./db/airflow:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5

  mlflow-run-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    env_file:
      - .env
    volumes:
      - ./db/mlflow:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "mlflow" ]
      interval: 5s
      retries: 5

  airflow-run-redis:
    image: redis:7
    env_file:
      - .env
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  backend-run-mongodb:
    image: mongo:6
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================
  # === COMPOSANTS AIRFLOW
  # ========================================
  airflow-init:
    <<: *airflow-common
    entrypoint: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com --password admin &&
      python /opt/airflow/import_env_to_airflow.py
      "
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./import_env_to_airflow.py:/opt/airflow/import_env_to_airflow.py

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    env_file:
      - .env
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
#      backend-run-mongodb:
#      backend-run-mlflow:

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    env_file:
      - .env
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"  # Permet une gestion propre des signaux d’arrêt
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"' ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    env_file:
      - .env
    command:
      - bash
      - -c
      - airflow

  # ========================================
  # === BACKEND FASTAPI
  # ========================================
  backend-run-api:
    build: ./backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8500
    env_file:
      - .env
    ports:
      - "8500:8500"
    volumes:
      - ./backend:/app
    depends_on:
      - backend-run-mongodb

  # ========================================
  # === FRONTEND STREAMLIT
  # ========================================
  frontend-run-ui:
    build: ./frontend
    command: streamlit run app.py --server.port=8501 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --server.runOnSave true
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-run-api

  # ========================================
  # === MLFLOW SERVER
  # ========================================
  backend-run-mlflow:
    build: ./mlflow
    command: mlflow server --backend-store-uri postgresql+psycopg2://mlflow:mlflow@mlflow-run-postgres/mlflow --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5050
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns
    depends_on:
      mlflow-run-postgres:
        condition: service_healthy

# ========================================
# === VOLUMES PERSISTANTS
# ========================================
volumes:
  mongo:
  airflow:
  mlflow:
  mlruns:
