FROM python:3.9-slim

WORKDIR /app

# Copier tous les fichiers Python et le requirements.txt depuis le contexte
COPY *.py .
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Optionnel : créer un sous-dossier pour les tests si besoin
# COPY tests/ /app/tests/