FROM python:3.9-slim

WORKDIR /app

# Installez les dépendances nécessaires aux tests
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiez le code de test
COPY jenkins/tests/ /app/tests/ 
# Le point final ('.') va copier les fichiers qui sont dans jenkins/tests/ 
# (vos scripts de test, etc.)