FROM python:3.9-slim

WORKDIR /app

# 1. Copie du fichier de dépendance spécifique aux tests
# Le contexte de build étant la racine (.), le chemin est relatif à la racine.
COPY jenkins/tests/requirements_tests.txt .
RUN pip install --no-cache-dir -r requirements_tests.txt

# 2. Copie du code de test et du code d'application
# Le chemin DOIT être spécifié depuis la racine du contexte (la racine du projet)
# Copie des fichiers de code que l'image de test doit exécuter (test scripts, etl_process.py, etc.)
COPY jenkins/tests/ /app/tests/ 
COPY jenkins/etl_process.py /app/etl_process.py
COPY jenkins/upload_s3.py /app/upload_s3.py